/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeAPartnerRouteImport } from './routes/become-a-partner'
import { Route as BeeFarmingRouteImport } from './routes/bee-farming'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BulkGiftingRouteImport } from './routes/bulk-gifting'
import { Route as BulkOrdersRouteImport } from './routes/bulk-orders'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporateGiftingRouteImport } from './routes/corporate-gifting'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GiftHampersRouteImport } from './routes/gift-hampers'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as PrivateLabelRouteImport } from './routes/private-label'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminInstagramRouteImport } from './routes/admin.instagram'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminLoyaltyRouteImport } from './routes/admin.loyalty'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminMigrateCatalogRouteImport } from './routes/admin.migrate-catalog'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminRedirectsRouteImport } from './routes/admin.redirects'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStoriesRouteImport } from './routes/admin.stories'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWhoWeSupplyRouteImport } from './routes/admin.who-we-supply'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as AdminHomepageAnnouncementsRouteImport } from './routes/admin.homepage_.announcements'
import { Route as AdminHomepageCategoriesRouteImport } from './routes/admin.homepage_.categories'
import { Route as AdminHomepageProductsRouteImport } from './routes/admin.homepage_.products'
import { Route as AdminHomepageTrustRouteImport } from './routes/admin.homepage_.trust'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicSubmissionsRouteImport } from './routes/api/public/submissions'
import { Route as NewsletterConfirmTokenRouteImport } from './routes/newsletter.confirm.$token'
import { Route as NewsletterUnsubscribeTokenRouteImport } from './routes/newsletter.unsubscribe.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAPartnerRoute = BecomeAPartnerRouteImport.update({
  id: '/become-a-partner',
  path: '/become-a-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const BeeFarmingRoute = BeeFarmingRouteImport.update({
  id: '/bee-farming',
  path: '/bee-farming',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkGiftingRoute = BulkGiftingRouteImport.update({
  id: '/bulk-gifting',
  path: '/bulk-gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrdersRoute = BulkOrdersRouteImport.update({
  id: '/bulk-orders',
  path: '/bulk-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateGiftingRoute = CorporateGiftingRouteImport.update({
  id: '/corporate-gifting',
  path: '/corporate-gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftHampersRoute = GiftHampersRouteImport.update({
  id: '/gift-hampers',
  path: '/gift-hampers',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLabelRoute = PrivateLabelRouteImport.update({
  id: '/private-label',
  path: '/private-label',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstagramRoute = AdminInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoyaltyRoute = AdminLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMigrateCatalogRoute = AdminMigrateCatalogRouteImport.update({
  id: '/migrate-catalog',
  path: '/migrate-catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedirectsRoute = AdminRedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoriesRoute = AdminStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWhoWeSupplyRoute = AdminWhoWeSupplyRouteImport.update({
  id: '/who-we-supply',
  path: '/who-we-supply',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const AdminHomepageAnnouncementsRoute =
  AdminHomepageAnnouncementsRouteImport.update({
    id: '/homepage_/announcements',
    path: '/homepage/announcements',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminHomepageCategoriesRoute = AdminHomepageCategoriesRouteImport.update({
  id: '/homepage_/categories',
  path: '/homepage/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageProductsRoute = AdminHomepageProductsRouteImport.update({
  id: '/homepage_/products',
  path: '/homepage/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageTrustRoute = AdminHomepageTrustRouteImport.update({
  id: '/homepage_/trust',
  path: '/homepage/trust',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubmissionsRoute = ApiPublicSubmissionsRouteImport.update({
  id: '/api/public/submissions',
  path: '/api/public/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfirmTokenRoute = NewsletterConfirmTokenRouteImport.update({
  id: '/newsletter/confirm/$token',
  path: '/newsletter/confirm/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterUnsubscribeTokenRoute =
  NewsletterUnsubscribeTokenRouteImport.update({
    id: '/newsletter/unsubscribe/$token',
    path: '/newsletter/unsubscribe/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/bee-farming': typeof BeeFarmingRoute
  '/blog': typeof BlogRouteWithChildren
  '/bulk-gifting': typeof BulkGiftingRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/corporate-gifting': typeof CorporateGiftingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gift-hampers': typeof GiftHampersRoute
  '/our-story': typeof OurStoryRoute
  '/private-label': typeof PrivateLabelRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/migrate-catalog': typeof AdminMigrateCatalogRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/who-we-supply': typeof AdminWhoWeSupplyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/homepage/announcements': typeof AdminHomepageAnnouncementsRoute
  '/admin/homepage/categories': typeof AdminHomepageCategoriesRoute
  '/admin/homepage/products': typeof AdminHomepageProductsRoute
  '/admin/homepage/trust': typeof AdminHomepageTrustRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/submissions': typeof ApiPublicSubmissionsRoute
  '/newsletter/confirm/$token': typeof NewsletterConfirmTokenRoute
  '/newsletter/unsubscribe/$token': typeof NewsletterUnsubscribeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/bee-farming': typeof BeeFarmingRoute
  '/blog': typeof BlogRouteWithChildren
  '/bulk-gifting': typeof BulkGiftingRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/corporate-gifting': typeof CorporateGiftingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gift-hampers': typeof GiftHampersRoute
  '/our-story': typeof OurStoryRoute
  '/private-label': typeof PrivateLabelRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/migrate-catalog': typeof AdminMigrateCatalogRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/who-we-supply': typeof AdminWhoWeSupplyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/admin/homepage/announcements': typeof AdminHomepageAnnouncementsRoute
  '/admin/homepage/categories': typeof AdminHomepageCategoriesRoute
  '/admin/homepage/products': typeof AdminHomepageProductsRoute
  '/admin/homepage/trust': typeof AdminHomepageTrustRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/submissions': typeof ApiPublicSubmissionsRoute
  '/newsletter/confirm/$token': typeof NewsletterConfirmTokenRoute
  '/newsletter/unsubscribe/$token': typeof NewsletterUnsubscribeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/bee-farming': typeof BeeFarmingRoute
  '/blog': typeof BlogRouteWithChildren
  '/bulk-gifting': typeof BulkGiftingRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/corporate-gifting': typeof CorporateGiftingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gift-hampers': typeof GiftHampersRoute
  '/our-story': typeof OurStoryRoute
  '/private-label': typeof PrivateLabelRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/migrate-catalog': typeof AdminMigrateCatalogRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/who-we-supply': typeof AdminWhoWeSupplyRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/homepage_/announcements': typeof AdminHomepageAnnouncementsRoute
  '/admin/homepage_/categories': typeof AdminHomepageCategoriesRoute
  '/admin/homepage_/products': typeof AdminHomepageProductsRoute
  '/admin/homepage_/trust': typeof AdminHomepageTrustRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/submissions': typeof ApiPublicSubmissionsRoute
  '/newsletter/confirm/$token': typeof NewsletterConfirmTokenRoute
  '/newsletter/unsubscribe/$token': typeof NewsletterUnsubscribeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/become-a-partner'
    | '/bee-farming'
    | '/blog'
    | '/bulk-gifting'
    | '/bulk-orders'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/corporate-gifting'
    | '/forgot-password'
    | '/gift-hampers'
    | '/our-story'
    | '/private-label'
    | '/reset-password'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/track-order'
    | '/wishlist'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/instagram'
    | '/admin/inventory'
    | '/admin/loyalty'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/migrate-catalog'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/redirects'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/submissions'
    | '/admin/users'
    | '/admin/who-we-supply'
    | '/auth/callback'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/shop/$slug'
    | '/admin/'
    | '/collections/'
    | '/shop/'
    | '/admin/homepage/announcements'
    | '/admin/homepage/categories'
    | '/admin/homepage/products'
    | '/admin/homepage/trust'
    | '/api/public/health'
    | '/api/public/submissions'
    | '/newsletter/confirm/$token'
    | '/newsletter/unsubscribe/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/become-a-partner'
    | '/bee-farming'
    | '/blog'
    | '/bulk-gifting'
    | '/bulk-orders'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/corporate-gifting'
    | '/forgot-password'
    | '/gift-hampers'
    | '/our-story'
    | '/private-label'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/track-order'
    | '/wishlist'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/instagram'
    | '/admin/inventory'
    | '/admin/loyalty'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/migrate-catalog'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/redirects'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/submissions'
    | '/admin/users'
    | '/admin/who-we-supply'
    | '/auth/callback'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/shop/$slug'
    | '/admin'
    | '/collections'
    | '/shop'
    | '/admin/homepage/announcements'
    | '/admin/homepage/categories'
    | '/admin/homepage/products'
    | '/admin/homepage/trust'
    | '/api/public/health'
    | '/api/public/submissions'
    | '/newsletter/confirm/$token'
    | '/newsletter/unsubscribe/$token'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/become-a-partner'
    | '/bee-farming'
    | '/blog'
    | '/bulk-gifting'
    | '/bulk-orders'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/corporate-gifting'
    | '/forgot-password'
    | '/gift-hampers'
    | '/our-story'
    | '/private-label'
    | '/reset-password'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/track-order'
    | '/wishlist'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/instagram'
    | '/admin/inventory'
    | '/admin/loyalty'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/migrate-catalog'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/redirects'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/submissions'
    | '/admin/users'
    | '/admin/who-we-supply'
    | '/auth_/callback'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/shop/$slug'
    | '/admin/'
    | '/collections/'
    | '/shop/'
    | '/admin/homepage_/announcements'
    | '/admin/homepage_/categories'
    | '/admin/homepage_/products'
    | '/admin/homepage_/trust'
    | '/api/public/health'
    | '/api/public/submissions'
    | '/newsletter/confirm/$token'
    | '/newsletter/unsubscribe/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeAPartnerRoute: typeof BecomeAPartnerRoute
  BeeFarmingRoute: typeof BeeFarmingRoute
  BlogRoute: typeof BlogRouteWithChildren
  BulkGiftingRoute: typeof BulkGiftingRoute
  BulkOrdersRoute: typeof BulkOrdersRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CorporateGiftingRoute: typeof CorporateGiftingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GiftHampersRoute: typeof GiftHampersRoute
  OurStoryRoute: typeof OurStoryRoute
  PrivateLabelRoute: typeof PrivateLabelRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WishlistRoute: typeof WishlistRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicSubmissionsRoute: typeof ApiPublicSubmissionsRoute
  NewsletterConfirmTokenRoute: typeof NewsletterConfirmTokenRoute
  NewsletterUnsubscribeTokenRoute: typeof NewsletterUnsubscribeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-partner': {
      id: '/become-a-partner'
      path: '/become-a-partner'
      fullPath: '/become-a-partner'
      preLoaderRoute: typeof BecomeAPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bee-farming': {
      id: '/bee-farming'
      path: '/bee-farming'
      fullPath: '/bee-farming'
      preLoaderRoute: typeof BeeFarmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-gifting': {
      id: '/bulk-gifting'
      path: '/bulk-gifting'
      fullPath: '/bulk-gifting'
      preLoaderRoute: typeof BulkGiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-orders': {
      id: '/bulk-orders'
      path: '/bulk-orders'
      fullPath: '/bulk-orders'
      preLoaderRoute: typeof BulkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-gifting': {
      id: '/corporate-gifting'
      path: '/corporate-gifting'
      fullPath: '/corporate-gifting'
      preLoaderRoute: typeof CorporateGiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-hampers': {
      id: '/gift-hampers'
      path: '/gift-hampers'
      fullPath: '/gift-hampers'
      preLoaderRoute: typeof GiftHampersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-label': {
      id: '/private-label'
      path: '/private-label'
      fullPath: '/private-label'
      preLoaderRoute: typeof PrivateLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instagram': {
      id: '/admin/instagram'
      path: '/instagram'
      fullPath: '/admin/instagram'
      preLoaderRoute: typeof AdminInstagramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loyalty': {
      id: '/admin/loyalty'
      path: '/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof AdminLoyaltyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/migrate-catalog': {
      id: '/admin/migrate-catalog'
      path: '/migrate-catalog'
      fullPath: '/admin/migrate-catalog'
      preLoaderRoute: typeof AdminMigrateCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redirects': {
      id: '/admin/redirects'
      path: '/redirects'
      fullPath: '/admin/redirects'
      preLoaderRoute: typeof AdminRedirectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stories': {
      id: '/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AdminStoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/who-we-supply': {
      id: '/admin/who-we-supply'
      path: '/who-we-supply'
      fullPath: '/admin/who-we-supply'
      preLoaderRoute: typeof AdminWhoWeSupplyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/homepage_/announcements': {
      id: '/admin/homepage_/announcements'
      path: '/homepage/announcements'
      fullPath: '/admin/homepage/announcements'
      preLoaderRoute: typeof AdminHomepageAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage_/categories': {
      id: '/admin/homepage_/categories'
      path: '/homepage/categories'
      fullPath: '/admin/homepage/categories'
      preLoaderRoute: typeof AdminHomepageCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage_/products': {
      id: '/admin/homepage_/products'
      path: '/homepage/products'
      fullPath: '/admin/homepage/products'
      preLoaderRoute: typeof AdminHomepageProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage_/trust': {
      id: '/admin/homepage_/trust'
      path: '/homepage/trust'
      fullPath: '/admin/homepage/trust'
      preLoaderRoute: typeof AdminHomepageTrustRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submissions': {
      id: '/api/public/submissions'
      path: '/api/public/submissions'
      fullPath: '/api/public/submissions'
      preLoaderRoute: typeof ApiPublicSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirm/$token': {
      id: '/newsletter/confirm/$token'
      path: '/newsletter/confirm/$token'
      fullPath: '/newsletter/confirm/$token'
      preLoaderRoute: typeof NewsletterConfirmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/unsubscribe/$token': {
      id: '/newsletter/unsubscribe/$token'
      path: '/newsletter/unsubscribe/$token'
      fullPath: '/newsletter/unsubscribe/$token'
      preLoaderRoute: typeof NewsletterUnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminInstagramRoute: typeof AdminInstagramRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoyaltyRoute: typeof AdminLoyaltyRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMigrateCatalogRoute: typeof AdminMigrateCatalogRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRedirectsRoute: typeof AdminRedirectsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoriesRoute: typeof AdminStoriesRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWhoWeSupplyRoute: typeof AdminWhoWeSupplyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminHomepageAnnouncementsRoute: typeof AdminHomepageAnnouncementsRoute
  AdminHomepageCategoriesRoute: typeof AdminHomepageCategoriesRoute
  AdminHomepageProductsRoute: typeof AdminHomepageProductsRoute
  AdminHomepageTrustRoute: typeof AdminHomepageTrustRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminInstagramRoute: AdminInstagramRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoyaltyRoute: AdminLoyaltyRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMigrateCatalogRoute: AdminMigrateCatalogRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRedirectsRoute: AdminRedirectsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoriesRoute: AdminStoriesRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWhoWeSupplyRoute: AdminWhoWeSupplyRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminHomepageAnnouncementsRoute: AdminHomepageAnnouncementsRoute,
  AdminHomepageCategoriesRoute: AdminHomepageCategoriesRoute,
  AdminHomepageProductsRoute: AdminHomepageProductsRoute,
  AdminHomepageTrustRoute: AdminHomepageTrustRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeAPartnerRoute: BecomeAPartnerRoute,
  BeeFarmingRoute: BeeFarmingRoute,
  BlogRoute: BlogRouteWithChildren,
  BulkGiftingRoute: BulkGiftingRoute,
  BulkOrdersRoute: BulkOrdersRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CorporateGiftingRoute: CorporateGiftingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GiftHampersRoute: GiftHampersRoute,
  OurStoryRoute: OurStoryRoute,
  PrivateLabelRoute: PrivateLabelRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackOrderRoute: TrackOrderRoute,
  WishlistRoute: WishlistRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicSubmissionsRoute: ApiPublicSubmissionsRoute,
  NewsletterConfirmTokenRoute: NewsletterConfirmTokenRoute,
  NewsletterUnsubscribeTokenRoute: NewsletterUnsubscribeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
