// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Public Supabase credentials (anon key — NOT a secret, protected by RLS)
const FALLBACK_SUPABASE_URL = "https://lxdkcqdkfuuqjudsysrr.supabase.co";
const FALLBACK_SUPABASE_KEY = "sb_publishable_E3rv2tJCU_jTt1wL_TyWDQ_u1_9ztgY";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to window.__ENV for runtime injection, then process.env for SSR
  // Final fallback: hardcoded public values (safe — these are publishable, protected by RLS)
  const envSource = typeof window !== 'undefined' ? (window as any).__ENV || {} : {};
  const SUPABASE_URL = import.meta.env?.VITE_SUPABASE_URL || envSource.SUPABASE_URL || (typeof process !== 'undefined' ? process.env.SUPABASE_URL : undefined) || FALLBACK_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY || envSource.SUPABASE_PUBLISHABLE_KEY || (typeof process !== 'undefined' ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined) || FALLBACK_SUPABASE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: (() => {
        if (typeof window === 'undefined') return undefined;
        try {
          const testKey = '__storage_test__';
          window.localStorage.setItem(testKey, testKey);
          window.localStorage.removeItem(testKey);
          return window.localStorage;
        } catch (e) {
          console.warn("localStorage not available, likely due to iframe restrictions. Falling back to memory storage.");
          return undefined;
        }
      })(),
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: (url, options) => {
        // Do not apply the strict 8-second timeout to storage uploads, as large videos take longer
        if (typeof url === "string" && url.includes("/storage/v1/object")) {
          return fetch(url, options);
        }
        const strictSignal = options?.signal
          ? AbortSignal.any([options.signal, AbortSignal.timeout(8000)])
          : AbortSignal.timeout(8000);
        return fetch(url, { ...options, signal: strictSignal });
      },
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

